language: java
jdk:
  - oraclejdk7
  - openjdk7

env:
  - TRAVIS=true STRICT_FILE_CHECKING=true

services:
  - cassandra

install:
  - mvn install -Dmaven.test.skip

script: 
  - mvn verify --quiet

notifications:
  email:
    recepients:
      - gdusbabek@gmail.com
